export const languagesArray = [
  { name: "Afar", flag: "dj" },
  { name: "Abkhazian", flag: "ge" },
  { name: "Afrikaans", flag: "za" },
  { name: "Akan", flag: "gh" },
  { name: "Amharic", flag: "et" },
  { name: "Arabic", flag: "sa" },
  { name: "Assamese", flag: "in" },
  { name: "Awadhi", flag: "in" },
  { name: "Aymara", flag: "bo" },
  { name: "Azerbaijani", flag: "az" },
  { name: "Bhojpuri", flag: "in" },
  { name: "Maithili", flag: "np" },
  { name: "Bashkir", flag: "ru" },
  { name: "Belarussian", flag: "by" },
  { name: "Bulgarian", flag: "bg" },
  { name: "Bihari", flag: "in" },
  { name: "Bislama", flag: "vu" },
  { name: "Balochi", flag: "pk" },
  { name: "Bengali", flag: "bd" },
  { name: "Tibetan", flag: "cn" },
  { name: "Breton", flag: "fr" },
  { name: "Catalan", flag: "language-ca" }, // language without country flag
  { name: "Cebuano", flag: "ph" },
  { name: "Chechen", flag: "language-ce" }, // language without country flag
  { name: "Corsican", flag: "fr" },
  { name: "Czech", flag: "cz" },
  { name: "Welsh", flag: "language-cy" }, // language without country flag
  { name: "Danish", flag: "dk" },
  { name: "German", flag: "de" },
  { name: "Dakhini", flag: "in" },
  { name: "Bhutani", flag: "bt" },
  { name: "Greek", flag: "gr" },
  { name: "English", flag: "gb" },
  { name: "Esperanto", flag: "language-eo" }, // language without country flag
  { name: "Spanish", flag: "es" },
  { name: "Estonian", flag: "ee" },
  { name: "Basque", flag: "language-eu" }, // language without country flag
  { name: "Persian", flag: "ir" },
  { name: "Finnish", flag: "fi" },
  { name: "Fiji", flag: "fj" },
  { name: "Faeroese", flag: "fo" },
  { name: "French", flag: "fr" },
  { name: "Frisian", flag: "nl" },
  { name: "Irish", flag: "ie" },
  { name: "Scottish Gaelic", flag: "language-gd" }, // language without country flag
  { name: "Galician", flag: "language-gl" }, // language without country flag
  { name: "Guarani", flag: "py" },
  { name: "Gujarati", flag: "in" },
  { name: "Hausa", flag: "ne" },
  { name: "Hindi", flag: "in" },
  { name: "Croatian", flag: "hr" },
  { name: "Haitian Creole", flag: "ht" },
  { name: "Hungarian", flag: "hu" },
  { name: "Armenian", flag: "am" },
  { name: "Interlingua", flag: "language-ia" }, // language without country flag
  { name: "Interlingue", flag: "language-ie" }, // language without country flag
  { name: "Inupiak", flag: "language-ik" }, // language without country flag
  { name: "Indonesian", flag: "id" },
  { name: "Icelandic", flag: "is" },
  { name: "Italian", flag: "it" },
  { name: "Hebrew", flag: "il" },
  { name: "Japanese", flag: "jp" },
  { name: "Yiddish", flag: "language-ji" }, // language without country flag
  { name: "Javanese", flag: "id" },
  { name: "Georgian", flag: "ge" },
  { name: "Kabyle", flag: "dz" },
  { name: "Konkani", flag: "in" },
  { name: "Kazakh", flag: "kz" },
  { name: "Greenlandic", flag: "gl" },
  { name: "Khmer", flag: "kh" },
  { name: "Kannada", flag: "in" },
  { name: "Korean", flag: "kr" },
  { name: "Kashmiri", flag: "in" },
  { name: "Kurdish", flag: "iq" },
  { name: "Kirghiz", flag: "kg" },
  { name: "Latin", flag: "va" },
  { name: "Luxembourgish", flag: "lu" },
  { name: "Lombard", flag: "it" },
  { name: "Lingala", flag: "cg" },
  { name: "Laothian", flag: "la" },
  { name: "Lithuanian", flag: "lt" },
  { name: "Latvian", flag: "lv" },
  { name: "Malagasy", flag: "mg" },
  { name: "Maori", flag: "nz" },
  { name: "Macedonian", flag: "mk" },
  { name: "Malayalam", flag: "in" },
  { name: "Mongolian", flag: "mn" },
  { name: "Moldavian", flag: "md" },
  { name: "Marathi", flag: "in" },
  { name: "Malay", flag: "my" },
  { name: "Maltese", flag: "mt" },
  { name: "Makhuwa", flag: "mz" },
  { name: "Marwari", flag: "in" },
  { name: "Burmese", flag: "mm" },
  { name: "Nauru", flag: "nr" },
  { name: "Nepali", flag: "np" },
  { name: "Dutch", flag: "nl" },
  { name: "Norwegian", flag: "no" },
  { name: "Occitan", flag: "fr" },
  { name: "Oromo", flag: "et" },
  { name: "Oriya", flag: "in" },
  { name: "Punjabi", flag: "pk" },
  { name: "Polish", flag: "pl" },
  { name: "Pashto", flag: "af" },
  { name: "Portuguese", flag: "pt" },
  { name: "Quechua", flag: "pe" },
  { name: "Rifian", flag: "ma" },
  { name: "Rhaeto-Romance", flag: "ch" },
  { name: "Kirundi", flag: "bi" },
  { name: "Romanian", flag: "ro" },
  { name: "Russian", flag: "ru" },
  { name: "Kinyarwanda", flag: "rw" },
  { name: "Sanskrit", flag: "in" },
  { name: "Sindhi", flag: "pk" },
  { name: "Sangro", flag: "cf" },
  { name: "Serbo-Croatian", flag: "rs" },
  { name: "Sinhalese", flag: "lk" },
  { name: "Slovak", flag: "sk" },
  { name: "Slovenian", flag: "si" },
  { name: "Samoan", flag: "ws" },
  { name: "Shona", flag: "zw" },
  { name: "Somali", flag: "so" },
  { name: "Albanian", flag: "al" },
  { name: "Serbian", flag: "rs" },
  { name: "Siswati", flag: "sz" },
  { name: "Sesotho", flag: "ls" },
  { name: "Sundanese", flag: "id" },
  { name: "Swedish", flag: "se" },
  { name: "Swahili", flag: "ke" },
  { name: "Tamil", flag: "lk" },
  { name: "Telugu", flag: "in" },
  { name: "Tajik", flag: "tj" },
  { name: "Thai", flag: "th" },
  { name: "Tigrinya", flag: "er" },
  { name: "Turkmen", flag: "tm" },
  { name: "Tagalog", flag: "ph" },
  { name: "Tuareg", flag: "language-tm" }, // language without country flag
  { name: "Setswana", flag: "bw" },
  { name: "Tonga", flag: "to" },
  { name: "Turkish", flag: "tr" },
  { name: "Tsonga", flag: "za" },
  { name: "Tatar", flag: "ru" },
  { name: "Twi", flag: "gh" },
  { name: "Tamazight", flag: "language-tz" }, // language without country flag
  { name: "Uyghur", flag: "cn" },
  { name: "Ukrainian", flag: "ua" },
  { name: "Urdu", flag: "pk" },
  { name: "Uzbek", flag: "uz" },
  { name: "Vietnamese", flag: "vn" },
  { name: "Volapuk", flag: "language-vo" }, // language without country flag
  { name: "Wolof", flag: "sn" },
  { name: "Xhosa", flag: "za" },
  { name: "Yoruba", flag: "ng" },
  { name: "Chinese", flag: "cn" },
  { name: "Zulu", flag: "za" },
];
