export const loadingPhrases = [
  "Loading, please wait...",
  "Please wait while we load your data...",
  "Loading, just a moment please...",
  "Hold on while we load the page...",
  "One moment please, loading in progress...",
  "We are currently loading the necessary resources...",
  "Please wait while we retrieve the information...",
  "Hang tight while we load the content...",
  "The page is loading, just a second...",
  "Loading, please wait a moment...",
  "We are loading the requested data, just a moment...",
  "Just a moment while we load the page...",
  "Please wait while we load the resources needed...",
];
export const didYouKnowPhrases = [
  "Did you know that the Earth is the densest planet in the Solar System?",
  "Did you know that the human nose can detect over 1 trillion different scents?",
  "Did you know that the shortest war in history was between Britain and Zanzibar in 1896, and lasted only 38 minutes?",
  "Did you know that the average person spends 6 months of their lifetime waiting on a red light to turn green?",
  "Did you know that the world's largest snowflake on record was 15 inches wide and 8 inches thick?",
  "Did you know that the first computer mouse was made of wood?",
  "Did you know that the longest wedding veil was worn by an Australian woman and measured 5.8 miles long?",
  "Did you know that the world's oldest cat lived to be 38 years old?",
  "Did you know that the Mona Lisa painting is only 30 inches tall and 21 inches wide?",
  "Did you know that the world's largest pumpkin weighed over 2,600 pounds?",
  "Did you know that the Earth's atmosphere is made up of 78% nitrogen, 21% oxygen, and trace amounts of other gases?",
  "Did you know that the tallest building in the world is the Burj Khalifa, which is over 2,700 feet tall?",
  "Did you know that the largest animal on Earth is the blue whale, which can grow up to 100 feet long and weigh over 200 tons?",
  "Did you know that the Earth has over 1 million known species of insects?",
  "Did you know that the shortest war in history was between Britain and Zanzibar in 1896, and lasted only 38 minutes?",
  "Did you know that the programmer created this site for about 3 months?",
  "Did you know that the average person spends 6 months of their lifetime waiting on a red light to turn green?",
  "Did you know that the Earth's crust is made up of over 20 tectonic plates that are constantly moving?",
  "Did you know that the largest living organism on Earth is a fungus called Armillaria ostoyae, which covers over 2,200 acres in Oregon?",
  "Did you know that the oldest known message in a bottle was found in Germany in 2015 and was 108 years old?",
  "Did you know that the world's largest snowflake on record was 15 inches wide and 8 inches thick?",
  "Did you know that the first computer mouse was made of wood?",
  "Did you know that the longest wedding veil was worn by an Australian woman and measured 5.8 miles long?",
  "Did you know that the world's oldest cat lived to be 38 years old?",
  "Did you know that the Mona Lisa painting is only 30 inches tall and 21 inches wide?",
  "Did you know that the world's largest pumpkin weighed over 2,600 pounds?",
  "Did you know that the Earth's oceans are home to over 70% of the world's biodiversity?",
  "Did you know that the Earth's atmosphere is constantly being replenished with oxygen produced by plants through the process of photosynthesis?",
  "Did you know that the Earth's atmosphere is made up of about 78% nitrogen, 21% oxygen, and trace amounts of other gases?",
  "Did you know that the Earth's oceans contain about 97% of the planet's water?",
  "Did you know that the Earth's atmosphere protects us from meteoroids and cosmic rays?",
  "Did you know that the Earth's atmosphere is made up of several layers, including the troposphere, stratosphere, mesosphere, thermosphere, and exosphere?",
  "Did you know that the Earth's atmosphere helps regulate the planet's temperature through the greenhouse effect?",
  "Did you know that the Earth's oceans contain over 20 million tons of gold?",
  "Did you know that the Earth's oceans are home to some of the world's most extreme environments, including the Mariana Trench, the deepest point on Earth?",
  "Did you know that the Earth's oceans contain over 95% of the planet's living space?",
];
